#!/bin/bash

# defult core_pattern
# |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
# use the same arglist for coregen with %p appended
# |/usr/local/sbin/coregen  %P %u %g %s %t %c %h %e %p
echo "|/usr/local/sbin/coregen %P %u %g %s %t %c %h %e %p" > /proc/sys/kernel/core_pattern
